apiVersion: apps/v1 #version of the Kubernetes API you're using to create this object
kind: Deployment  #What kind of object you want to create
metadata: #deployment name, helps uniquely identify the object
   name: userissuems

spec:  
  selector:
    matchLabels:
      app: userissuems 


  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: userissuems
    spec:   #What state you desire for the object

      containers:
      - name: userissuems #container name
        image: 'rummesalma/userissue' #image name
        ports:
        - containerPort: 9009 # demo runs on port 8484