version: '3.8'

services:
    
    user:
        build: user
        ports:
        -9011:9011
    userissue:
        build: userissue
        ports:
        -9009:9009
    conversation:        
        build: conversation
        ports:
        - 10001:10001

    

       
 
